---
# tasks file for mariadb_cluster_with_galera

- name: "Install Mariadb"
  ansible.builtin.include_tasks: mariadb/install.yaml
  when: galera_group_name_for_proxy_sql is not in group_names

- name: "Config master node"
  ansible.builtin.include_tasks: galera/config_master.yaml
  when: galera_group_name_for_master in group_names

- name: "Config slave nodes"
  ansible.builtin.include_tasks: galera/config_slave.yaml
  when: galera_group_name_for_slave in group_names

- name: "Config proxysql"
  ansible.builtin.include_tasks: proxy/install.yml
  when: galera_group_name_for_proxy_sql in group_names
