---
# tasks file for install mariadb
- name: "Install prerequisites"
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    force_apt_get: true
  loop: ['aptitude', 'python3', 'python3-pip']

 # Install MariaDB server and other packages
- name: "Install MariaDB Packages"
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop: ['mariadb-server', 'python3-pymysql', 'mariadb-client', 'vim', 'sudo']

# Start MariaDB Service
- name: "Start MariaDB service"
  ansible.builtin.systemd:
    name: mariadb
    enabled: true
    state: started

 # MariaDB Configuration
- name: "Sets the root password"
  community.mysql.mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  failed_when: false

- name: "Removes all anonymous user accounts"
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: "Removes the MySQL test database"
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: "Comment bind-address to localhost"
  ansible.builtin.replace:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: 'bind-address'
    replace: '#bind-address'
    backup: true

- name: "Restart server"
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
