---

#install proxysql and config it

- name: "Check if proxysql is installed"
  command: dpkg-query -W proxysql 
  register: proxysql_check_deb
  failed_when: proxysql_check_deb.rc > 1
  changed_when: proxysql_check_deb.rc == 1

- name: "Get deb packages"
  ansible.builtin.get_url:
    url: https://github.com/sysown/proxysql/releases/download/v2.2.0/proxysql_2.2.0-debian10_amd64.deb
    dest: /tmp/proxysql.deb
  when: proxysql_check_deb.rc == 1

- name: "Install my_package"
  apt: 
    deb: "/tmp/proxysql.deb"
  when: proxysql_check_deb.rc == 1


- name: "Enable and start service"
  ansible.builtin.systemd:
    name: proxysql
    enabled: yes
    state: started

- name: "Install mariadb client"
  apt: name=mariadb-client update_cache=yes state=latest

- name: "Create sql config"
  template:
    src: "../../templates/proxy/proxy_config.j2"
    dest: "/tmp/proxy_config.sql"

- name: "Run config"
  shell:
    cmd: mysql -u admin -padmin -h 127.0.0.1 -P6032 < /tmp/proxy_config.sql