---
# tasks file for config galera slave nodes

- name: Config slave nodes
  template:
    src: "../../templates/slave/galera_slave.j2"
    dest: "/etc/mysql/mariadb.conf.d/galera.cnf"

- name: Restart mariadb service 
  ansible.builtin.systemd:
    name: mariadb
    state: restarted



