---
# tasks file for config galera

- name: "Config master nodes"
  ansible.builtin.template:
    src: "master/galera_master.j2"
    dest: "/etc/mysql/mariadb.conf.d/galera.cnf"
    mode: 0644

- name: "Setup new galera cluster"
  ansible.builtin.command: galera_new_cluster
  changed_when: false

- name: "Restart mariadb service"
  ansible.builtin.systemd:
    name: mariadb
    state: restarted

- name: "Create demodb database test"
  community.mysql.mysql_db:
    name: "demodb_master"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: "Create monitor user"
  community.mysql.mysql_user:
    host: '%'
    name: "{{ galera_monitor_user }}"
    password: "{{ galera_monitor_password }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: "Create another demo database"
  community.mysql.mysql_db:
    name: "anotherdemodb_master"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: "Create demo user"
  community.mysql.mysql_user:
    host: '%'
    name: "{{ galera_demo_user }}"
    password: "{{ galera_demo_user_password }}"
    state: present
    priv: 'anotherdemodb_master.*:ALL'
    login_user: root
    login_password: "{{ mysql_root_password }}"
