all:
  
  children:
    galera:
      children:
        master:
          hosts:
            192.168.1.30:
              short_name: db-1
        slave:
          hosts:
            192.168.1.17:
              short_name: db-2
            192.168.1.27:
              short_name: db-3 
      vars:
        domain_name: hdpw-esgi.fr
  
  vars:
    ansible_port: 2222
    ansible_user: myuser
    ansible_ssh_user: myuser
    ansible_become_user: root
    ansible_become: true
    ansible_become_password: myuser
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
