all:
  
  children:
    galera:
      children:
        master:
          hosts:
            192.168.1.30: 
              
        slave:
          hosts:
            192.168.1.17:
            192.168.1.27:
               
      vars:
        short_names: ['db-1','db-2','db-3']
        domain_name: hdpw-esgi.fr
  
  vars:
    ansible_port: 2222
    ansible_user: myuser
    ansible_ssh_user: myuser
    ansible_become_user: root
    ansible_become: true
    ansible_become_password: myuser
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
