---
all:
  
  children:
    galera:
      children:
        galera_master:
          hosts:
            master-db.esgisrc.fr:
   
        galera_slave:
          hosts:
            slave1-db.esgisrc.fr:
            slave2-db.esgisrc.fr:

        galera_proxy_sql:
          hosts:
            proxy-db.esgisrc.fr:
      vars:
        #galera_hosts_short_names: ['master-db','slave1-db','slave2-db','proxy-db']
        #domain_name: "esgisrc.fr"

        # configs for mariadb
        mysql_root_password: "root"
        disable_default: true

        # configs for galera
        galera_group_name_for_master: "galera_master"
        galera_group_name_for_slave: "galera_slave"
        galera_group_name_for_proxy_sql: "galera_proxy_sql"

        galera_monitor_user: "monitor"
        galera_monitor_password: "monitor"

        galera_demo_user : "demouser"
        galera_demo_user_password: "demouser"

        # configs for proxysql
        proxy_sql_admin_password: "admin"

    glusterfs:
      children:
        glusterfs_master:
          hosts:
            file01-gfs.esgisrc.fr:
            file02-gfs.esgisrc.fr:
      vars:
        glusterfs_group_name: "glusterfs"
        gluster_volume_name: "volumegluster"
        gluster_bricks_path: "/gluster-share"

    haproxy:
      children:
        web_servers:
          hosts:
            web01.esgisrc.fr:
            web02.esgisrc.fr:
            web03.esgisrc.fr:
        
        web_load_balancer:
          hosts:
            haproxy.esgisrc.fr:
  
  vars:
    ansible_port: 2222
    ansible_user: myuser
    ansible_ssh_user: myuser
    ansible_become_user: root
    ansible_become: true
    ansible_become_password: myuser
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
