---
- hosts: galera.master
  gather_facts: no
  remote_user: myuser

  tasks:
    - name: show templating results
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.template', './test.j2') }}"
      when: '"galera_master" in group_names'
